const TRANSLATION_KEYS = [
    'title_main',
    'subtitle_main',
    'mode_normal',
    'mode_competition',
    'label_status',
    'label_moves',
    'label_timer',
    'label_scramble',
    'scramble_placeholder',
    'scramble_in_progress',
    'speed_label',
    'speed_fast',
    'speed_slow',
    'speed_unit_suffix',
    'language_label',
    'language_option_ko',
    'language_option_zh',
    'language_option_en',
    'language_option_ja',
    'language_option_ar',
    'language_option_hi',
    'instruction_title',
    'instruction_face_controls',
    'instruction_left_keys',
    'instruction_right_keys',
    'instruction_view',
    'instruction_undo',
    'instruction_mobile',
    'btn_scramble',
    'btn_reset',
    'btn_undo',
    'btn_solution',
    'solution_header',
    'solution_apply',
    'solution_close',
    'solution_placeholder',
    'solution_processing',
    'solution_applied_message',
    'solution_already_solved',
    'leaderboard_title',
    'leaderboard_clear',
    'leaderboard_empty',
    'meta_moves_prefix',
    'meta_penalty',
    'meta_scramble_prefix',
    'dnf_label',
    'status_complete',
    'status_in_progress',
    'status_preparing',
    'status_hold',
    'status_inspecting',
    'status_solving',
    'status_failed',
    'competition_hint',
    'overlay_prepare_title',
    'overlay_prepare_message',
    'overlay_ready_title',
    'overlay_ready_message',
    'overlay_shuffle_failed_title',
    'overlay_shuffle_failed_message',
    'overlay_retry_title',
    'overlay_retry_message',
    'overlay_hold_title',
    'overlay_hold_message',
    'overlay_inspection_title',
    'overlay_inspection_message',
    'overlay_inspection_penalty_message',
    'overlay_fail_title',
    'overlay_fail_timeout_message',
    'overlay_fail_general_message',
    'overlay_result_title',
    'overlay_result_message_prefix',
    'overlay_result_penalty_suffix',
    'overlay_solution_disabled_title',
    'overlay_solution_disabled_message',
    'timer_penalty_suffix',
    'inspection_timer_suffix',
    'menu_open',
    'menu_close'
];

const SUPPORTED_TRANSLATION_LANGS = ['ko', 'zh', 'en', 'ja', 'ar', 'hi'];

const STRINGS = {
    ko: {
        title_main: '3x3x3 루빅스 큐브',
        subtitle_main: '온라인 루빅스 큐브 시뮬레이터',
        mode_normal: '일반 모드',
        mode_competition: '경기 모드',
        label_status: '상태',
        label_moves: '이동 횟수',
        label_timer: '타이머',
        label_scramble: '섞기 기록',
        scramble_placeholder: '섞기 중...',
        scramble_in_progress: '섞는 중...',
        speed_label: '속도',
        speed_fast: '빠름',
        speed_slow: '느림',
        speed_unit_suffix: '초',
        language_label: '언어',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: '조작법',
        instruction_face_controls: '면 회전 (왼손: 정방향 | 오른손: 역방향)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: '시점 회전: 마우스 드래그 또는 화살표 키',
        instruction_undo: '실행 취소: Z',
        instruction_mobile: '모바일: 면 탭 또는 스와이프',
        btn_scramble: '섞기',
        btn_reset: '초기화',
        btn_undo: '실행 취소',
        btn_solution: '해법 보기',
        solution_header: '해법',
        solution_apply: '적용',
        solution_close: '닫기',
        solution_placeholder: '해법을 계산하는 중...',
        solution_processing: '처리 중...',
        solution_applied_message: '해법이 적용되었습니다!',
        solution_already_solved: '이미 완성되었습니다!',
        leaderboard_title: '리더보드',
        leaderboard_clear: '초기화',
        leaderboard_empty: '아직 기록이 없습니다',
        meta_moves_prefix: '이동:',
        meta_penalty: '패널티',
        meta_scramble_prefix: '섞기:',
        dnf_label: 'DNF',
        status_complete: '완료',
        status_in_progress: '진행 중',
        status_preparing: '준비 중',
        status_hold: '홀드',
        status_inspecting: '검사 중',
        status_solving: '해결 중',
        status_failed: '실패',
        competition_hint: '스페이스바를 누르고 있으면 시작됩니다',
        overlay_prepare_title: '준비',
        overlay_prepare_message: '스페이스바를 누르고 있으세요',
        overlay_ready_title: '준비 완료!',
        overlay_ready_message: '스페이스바를 떼면 시작됩니다',
        overlay_shuffle_failed_title: '섞기 실패',
        overlay_shuffle_failed_message: '다시 시도해주세요',
        overlay_retry_title: '재시도',
        overlay_retry_message: '스페이스바를 눌러 다시 시도하세요',
        overlay_hold_title: '홀드',
        overlay_hold_message: '계속 누르고 있으세요...',
        overlay_inspection_title: '검사 시간',
        overlay_inspection_message: '아무 키나 눌러 시작하세요',
        overlay_inspection_penalty_message: '+2초 패널티',
        overlay_fail_title: '실패',
        overlay_fail_timeout_message: '시간 초과! DNF',
        overlay_fail_general_message: '다시 시도하세요',
        overlay_result_title: '완료!',
        overlay_result_message_prefix: '시간:',
        overlay_result_penalty_suffix: '(패널티 포함)',
        overlay_solution_disabled_title: '해법 사용 불가',
        overlay_solution_disabled_message: '경기 모드에서는 해법을 사용할 수 없습니다',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: '검사',
        menu_open: '메뉴 열기',
        menu_close: '메뉴 닫기'
    },
    zh: {
        title_main: '3x3x3 魔方',
        subtitle_main: '在线魔方模拟器',
        mode_normal: '普通模式',
        mode_competition: '竞赛模式',
        label_status: '状态',
        label_moves: '移动次数',
        label_timer: '计时器',
        label_scramble: '打乱记录',
        scramble_placeholder: '打乱中...',
        scramble_in_progress: '正在打乱...',
        speed_label: '速度',
        speed_fast: '快',
        speed_slow: '慢',
        speed_unit_suffix: '秒',
        language_label: '语言',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: '操作说明',
        instruction_face_controls: '面旋转 (左手: 顺时针 | 右手: 逆时针)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: '视角旋转：鼠标拖动或方向键',
        instruction_undo: '撤销：Z',
        instruction_mobile: '移动端：点击面或滑动',
        btn_scramble: '打乱',
        btn_reset: '重置',
        btn_undo: '撤销',
        btn_solution: '查看解法',
        solution_header: '解法',
        solution_apply: '应用',
        solution_close: '关闭',
        solution_placeholder: '正在计算解法...',
        solution_processing: '处理中...',
        solution_applied_message: '解法已应用！',
        solution_already_solved: '已经完成！',
        leaderboard_title: '排行榜',
        leaderboard_clear: '清空',
        leaderboard_empty: '还没有记录',
        meta_moves_prefix: '移动：',
        meta_penalty: '罚时',
        meta_scramble_prefix: '打乱：',
        dnf_label: 'DNF',
        status_complete: '完成',
        status_in_progress: '进行中',
        status_preparing: '准备中',
        status_hold: '按住',
        status_inspecting: '检查中',
        status_solving: '解决中',
        status_failed: '失败',
        competition_hint: '按住空格键开始',
        overlay_prepare_title: '准备',
        overlay_prepare_message: '按住空格键',
        overlay_ready_title: '准备就绪！',
        overlay_ready_message: '松开空格键开始',
        overlay_shuffle_failed_title: '打乱失败',
        overlay_shuffle_failed_message: '请重试',
        overlay_retry_title: '重试',
        overlay_retry_message: '按空格键重试',
        overlay_hold_title: '按住',
        overlay_hold_message: '继续按住...',
        overlay_inspection_title: '检查时间',
        overlay_inspection_message: '按任意键开始',
        overlay_inspection_penalty_message: '+2秒罚时',
        overlay_fail_title: '失败',
        overlay_fail_timeout_message: '超时！DNF',
        overlay_fail_general_message: '请重试',
        overlay_result_title: '完成！',
        overlay_result_message_prefix: '时间：',
        overlay_result_penalty_suffix: '（含罚时）',
        overlay_solution_disabled_title: '解法不可用',
        overlay_solution_disabled_message: '竞赛模式下无法使用解法',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: '检查',
        menu_open: '打开菜单',
        menu_close: '关闭菜单'
    },
    en: {
        title_main: '3x3x3 Rubik\'s Cube',
        subtitle_main: 'Online Rubik\'s Cube Simulator',
        mode_normal: 'Normal Mode',
        mode_competition: 'Competition Mode',
        label_status: 'Status',
        label_moves: 'Moves',
        label_timer: 'Timer',
        label_scramble: 'Scramble',
        scramble_placeholder: 'Scrambling...',
        scramble_in_progress: 'Scrambling...',
        speed_label: 'Speed',
        speed_fast: 'Fast',
        speed_slow: 'Slow',
        speed_unit_suffix: 's',
        language_label: 'Language',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: 'Controls',
        instruction_face_controls: 'Face Rotation (Left: Clockwise | Right: Counter-clockwise)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: 'View Rotation: Mouse Drag or Arrow Keys',
        instruction_undo: 'Undo: Z',
        instruction_mobile: 'Mobile: Tap Face or Swipe',
        btn_scramble: 'Scramble',
        btn_reset: 'Reset',
        btn_undo: 'Undo',
        btn_solution: 'Show Solution',
        solution_header: 'Solution',
        solution_apply: 'Apply',
        solution_close: 'Close',
        solution_placeholder: 'Calculating solution...',
        solution_processing: 'Processing...',
        solution_applied_message: 'Solution applied!',
        solution_already_solved: 'Already solved!',
        leaderboard_title: 'Leaderboard',
        leaderboard_clear: 'Clear',
        leaderboard_empty: 'No records yet',
        meta_moves_prefix: 'Moves:',
        meta_penalty: 'Penalty',
        meta_scramble_prefix: 'Scramble:',
        dnf_label: 'DNF',
        status_complete: 'Complete',
        status_in_progress: 'In Progress',
        status_preparing: 'Preparing',
        status_hold: 'Hold',
        status_inspecting: 'Inspecting',
        status_solving: 'Solving',
        status_failed: 'Failed',
        competition_hint: 'Hold spacebar to start',
        overlay_prepare_title: 'Prepare',
        overlay_prepare_message: 'Hold spacebar',
        overlay_ready_title: 'Ready!',
        overlay_ready_message: 'Release spacebar to start',
        overlay_shuffle_failed_title: 'Scramble Failed',
        overlay_shuffle_failed_message: 'Please try again',
        overlay_retry_title: 'Retry',
        overlay_retry_message: 'Press spacebar to retry',
        overlay_hold_title: 'Hold',
        overlay_hold_message: 'Keep holding...',
        overlay_inspection_title: 'Inspection',
        overlay_inspection_message: 'Press any key to start',
        overlay_inspection_penalty_message: '+2s penalty',
        overlay_fail_title: 'Failed',
        overlay_fail_timeout_message: 'Timeout! DNF',
        overlay_fail_general_message: 'Please try again',
        overlay_result_title: 'Complete!',
        overlay_result_message_prefix: 'Time:',
        overlay_result_penalty_suffix: '(with penalty)',
        overlay_solution_disabled_title: 'Solution Disabled',
        overlay_solution_disabled_message: 'Solution is not available in competition mode',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: 'Inspection',
        menu_open: 'Open Menu',
        menu_close: 'Close Menu'
    },
    ja: {
        title_main: '3x3x3 ルービックキューブ',
        subtitle_main: 'オンライン ルービックキューブ シミュレーター',
        mode_normal: 'ノーマルモード',
        mode_competition: '競技モード',
        label_status: 'ステータス',
        label_moves: '手数',
        label_timer: 'タイマー',
        label_scramble: 'スクランブル',
        scramble_placeholder: 'スクランブル中...',
        scramble_in_progress: 'スクランブル中...',
        speed_label: '速度',
        speed_fast: '速い',
        speed_slow: '遅い',
        speed_unit_suffix: '秒',
        language_label: '言語',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: '操作方法',
        instruction_face_controls: '面の回転 (左手: 時計回り | 右手: 反時計回り)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: '視点回転：マウスドラッグまたは矢印キー',
        instruction_undo: '元に戻す：Z',
        instruction_mobile: 'モバイル：面をタップまたはスワイプ',
        btn_scramble: 'スクランブル',
        btn_reset: 'リセット',
        btn_undo: '元に戻す',
        btn_solution: '解法を見る',
        solution_header: '解法',
        solution_apply: '適用',
        solution_close: '閉じる',
        solution_placeholder: '解法を計算中...',
        solution_processing: '処理中...',
        solution_applied_message: '解法が適用されました！',
        solution_already_solved: 'すでに完成しています！',
        leaderboard_title: 'リーダーボード',
        leaderboard_clear: 'クリア',
        leaderboard_empty: 'まだ記録がありません',
        meta_moves_prefix: '手数：',
        meta_penalty: 'ペナルティ',
        meta_scramble_prefix: 'スクランブル：',
        dnf_label: 'DNF',
        status_complete: '完了',
        status_in_progress: '進行中',
        status_preparing: '準備中',
        status_hold: 'ホールド',
        status_inspecting: 'インスペクション中',
        status_solving: '解決中',
        status_failed: '失敗',
        competition_hint: 'スペースバーを押し続けると開始します',
        overlay_prepare_title: '準備',
        overlay_prepare_message: 'スペースバーを押し続けてください',
        overlay_ready_title: '準備完了！',
        overlay_ready_message: 'スペースバーを離すと開始します',
        overlay_shuffle_failed_title: 'スクランブル失敗',
        overlay_shuffle_failed_message: 'もう一度お試しください',
        overlay_retry_title: 'リトライ',
        overlay_retry_message: 'スペースバーを押してリトライ',
        overlay_hold_title: 'ホールド',
        overlay_hold_message: '押し続けてください...',
        overlay_inspection_title: 'インスペクション',
        overlay_inspection_message: '任意のキーを押して開始',
        overlay_inspection_penalty_message: '+2秒ペナルティ',
        overlay_fail_title: '失敗',
        overlay_fail_timeout_message: 'タイムアップ！DNF',
        overlay_fail_general_message: 'もう一度お試しください',
        overlay_result_title: '完了！',
        overlay_result_message_prefix: 'タイム：',
        overlay_result_penalty_suffix: '（ペナルティ込み）',
        overlay_solution_disabled_title: '解法が無効',
        overlay_solution_disabled_message: '競技モードでは解法を使用できません',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: 'インスペクション',
        menu_open: 'メニューを開く',
        menu_close: 'メニューを閉じる'
    },
    ar: {
        title_main: 'مكعب روبيك 3x3x3',
        subtitle_main: 'محاكي مكعب روبيك على الإنترنت',
        mode_normal: 'الوضع العادي',
        mode_competition: 'وضع المنافسة',
        label_status: 'الحالة',
        label_moves: 'التحركات',
        label_timer: 'المؤقت',
        label_scramble: 'الخلط',
        scramble_placeholder: 'جاري الخلط...',
        scramble_in_progress: 'جاري الخلط...',
        speed_label: 'السرعة',
        speed_fast: 'سريع',
        speed_slow: 'بطيء',
        speed_unit_suffix: 'ث',
        language_label: 'اللغة',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: 'التحكم',
        instruction_face_controls: 'دوران الوجه (يسار: باتجاه | يمين: عكس)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: 'دوران العرض: سحب الماوس أو مفاتيح الأسهم',
        instruction_undo: 'التراجع: Z',
        instruction_mobile: 'الجوال: اضغط على الوجه أو اسحب',
        btn_scramble: 'خلط',
        btn_reset: 'إعادة تعيين',
        btn_undo: 'تراجع',
        btn_solution: 'عرض الحل',
        solution_header: 'الحل',
        solution_apply: 'تطبيق',
        solution_close: 'إغلاق',
        solution_placeholder: 'جاري حساب الحل...',
        solution_processing: 'جاري المعالجة...',
        solution_applied_message: 'تم تطبيق الحل!',
        solution_already_solved: 'تم الحل بالفعل!',
        leaderboard_title: 'لوحة المتصدرين',
        leaderboard_clear: 'مسح',
        leaderboard_empty: 'لا توجد سجلات بعد',
        meta_moves_prefix: 'التحركات:',
        meta_penalty: 'جزاء',
        meta_scramble_prefix: 'الخلط:',
        dnf_label: 'DNF',
        status_complete: 'مكتمل',
        status_in_progress: 'قيد التنفيذ',
        status_preparing: 'جاري التحضير',
        status_hold: 'اضغط مع الاستمرار',
        status_inspecting: 'جاري الفحص',
        status_solving: 'جاري الحل',
        status_failed: 'فشل',
        competition_hint: 'اضغط مع الاستمرار على مسافة للبدء',
        overlay_prepare_title: 'تحضير',
        overlay_prepare_message: 'اضغط مع الاستمرار على مسافة',
        overlay_ready_title: 'جاهز!',
        overlay_ready_message: 'اترك مسافة للبدء',
        overlay_shuffle_failed_title: 'فشل الخلط',
        overlay_shuffle_failed_message: 'يرجى المحاولة مرة أخرى',
        overlay_retry_title: 'إعادة المحاولة',
        overlay_retry_message: 'اضغط على مسافة لإعادة المحاولة',
        overlay_hold_title: 'اضغط مع الاستمرار',
        overlay_hold_message: 'استمر في الضغط...',
        overlay_inspection_title: 'الفحص',
        overlay_inspection_message: 'اضغط على أي مفتاح للبدء',
        overlay_inspection_penalty_message: 'جزاء +2 ثانية',
        overlay_fail_title: 'فشل',
        overlay_fail_timeout_message: 'انتهى الوقت! DNF',
        overlay_fail_general_message: 'يرجى المحاولة مرة أخرى',
        overlay_result_title: 'مكتمل!',
        overlay_result_message_prefix: 'الوقت:',
        overlay_result_penalty_suffix: '(مع الجزاء)',
        overlay_solution_disabled_title: 'الحل معطل',
        overlay_solution_disabled_message: 'الحل غير متاح في وضع المنافسة',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: 'الفحص',
        menu_open: 'فتح القائمة',
        menu_close: 'إغلاق القائمة'
    },
    hi: {
        title_main: '3x3x3 रूबिक्स क्यूब',
        subtitle_main: 'ऑनलाइन रूबिक्स क्यूब सिम्युलेटर',
        mode_normal: 'सामान्य मोड',
        mode_competition: 'प्रतियोगिता मोड',
        label_status: 'स्थिति',
        label_moves: 'चालें',
        label_timer: 'टाइमर',
        label_scramble: 'स्क्रैम्बल',
        scramble_placeholder: 'स्क्रैम्बल हो रहा है...',
        scramble_in_progress: 'स्क्रैम्बल हो रहा है...',
        speed_label: 'गति',
        speed_fast: 'तेज़',
        speed_slow: 'धीमा',
        speed_unit_suffix: 'सेकंड',
        language_label: 'भाषा',
        language_option_ko: '한국어',
        language_option_zh: '中文',
        language_option_en: 'English',
        language_option_ja: '日本語',
        language_option_ar: 'العربية',
        language_option_hi: 'हिन्दी',
        instruction_title: 'नियंत्रण',
        instruction_face_controls: 'फेस घुमाना (बायां: दक्षिणावर्त | दायां: वामावर्त)',
        instruction_left_keys: 'Q=L  W=U  E=R  |  U=L\'  I=U\'  O=R\'',
        instruction_right_keys: 'A=F  S=D  D=B  |  J=F\'  K=D\'  L=B\'',
        instruction_view: 'व्यू घुमाना: माउस ड्रैग या एरो कीज़',
        instruction_undo: 'पूर्ववत करें: Z',
        instruction_mobile: 'मोबाइल: फेस टैप करें या स्वाइप करें',
        btn_scramble: 'स्क्रैम्बल',
        btn_reset: 'रीसेट',
        btn_undo: 'पूर्ववत करें',
        btn_solution: 'समाधान देखें',
        solution_header: 'समाधान',
        solution_apply: 'लागू करें',
        solution_close: 'बंद करें',
        solution_placeholder: 'समाधान की गणना हो रही है...',
        solution_processing: 'प्रोसेसिंग...',
        solution_applied_message: 'समाधान लागू किया गया!',
        solution_already_solved: 'पहले से ही हल हो चुका है!',
        leaderboard_title: 'लीडरबोर्ड',
        leaderboard_clear: 'साफ़ करें',
        leaderboard_empty: 'अभी तक कोई रिकॉर्ड नहीं',
        meta_moves_prefix: 'चालें:',
        meta_penalty: 'पेनल्टी',
        meta_scramble_prefix: 'स्क्रैम्बल:',
        dnf_label: 'DNF',
        status_complete: 'पूर्ण',
        status_in_progress: 'प्रगति में',
        status_preparing: 'तैयारी हो रही है',
        status_hold: 'होल्ड',
        status_inspecting: 'निरीक्षण हो रहा है',
        status_solving: 'हल हो रहा है',
        status_failed: 'विफल',
        competition_hint: 'शुरू करने के लिए स्पेसबार दबाए रखें',
        overlay_prepare_title: 'तैयारी',
        overlay_prepare_message: 'स्पेसबार दबाए रखें',
        overlay_ready_title: 'तैयार!',
        overlay_ready_message: 'शुरू करने के लिए स्पेसबार छोड़ें',
        overlay_shuffle_failed_title: 'स्क्रैम्बल विफल',
        overlay_shuffle_failed_message: 'कृपया पुनः प्रयास करें',
        overlay_retry_title: 'पुनः प्रयास',
        overlay_retry_message: 'पुनः प्रयास के लिए स्पेसबार दबाएं',
        overlay_hold_title: 'होल्ड',
        overlay_hold_message: 'दबाए रखें...',
        overlay_inspection_title: 'निरीक्षण',
        overlay_inspection_message: 'शुरू करने के लिए कोई भी कुंजी दबाएं',
        overlay_inspection_penalty_message: '+2 सेकंड पेनल्टी',
        overlay_fail_title: 'विफल',
        overlay_fail_timeout_message: 'समय समाप्त! DNF',
        overlay_fail_general_message: 'कृपया पुनः प्रयास करें',
        overlay_result_title: 'पूर्ण!',
        overlay_result_message_prefix: 'समय:',
        overlay_result_penalty_suffix: '(पेनल्टी के साथ)',
        overlay_solution_disabled_title: 'समाधान अक्षम',
        overlay_solution_disabled_message: 'प्रतियोगिता मोड में समाधान उपलब्ध नहीं है',
        timer_penalty_suffix: '+2',
        inspection_timer_suffix: 'निरीक्षण',
        menu_open: 'मेनू खोलें',
        menu_close: 'मेनू बंद करें'
    }
};

if (typeof window !== 'undefined') {
    window.STRINGS = STRINGS;
    window.TRANSLATION_KEYS = TRANSLATION_KEYS;
    window.SUPPORTED_TRANSLATION_LANGS = SUPPORTED_TRANSLATION_LANGS;
}
